# Generated by Django 4.2.6 on 2023-10-31 16:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('IdArea', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Problemas',
            fields=[
                ('IdProblema', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=250)),
                ('IdArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.areas')),
            ],
        ),
    ]
