# Generated by Django 4.2.6 on 2023-11-01 15:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('IdPersona', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=250)),
                ('ApellidoP', models.CharField(max_length=250)),
                ('ApellidoM', models.CharField(max_length=250)),
                ('Rol', models.CharField(max_length=100)),
                ('IdArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.areas')),
            ],
        ),
    ]
