# Generated by Django 4.2.6 on 2023-11-01 16:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_personas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencias',
            fields=[
                ('IdAgencia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Agencia', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Distritos',
            fields=[
                ('IdDistrito', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Distrito', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('IdModulo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Modulo', models.CharField(max_length=500)),
                ('AgenciaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agencias')),
            ],
        ),
        migrations.AddField(
            model_name='agencias',
            name='IdDistrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.distritos'),
        ),
    ]
