# Generated by Django 4.2.6 on 2023-11-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agencias_distritos_modulos_agencias_iddistrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencias',
            old_name='IdDistrito',
            new_name='DistritoId',
        ),
        migrations.RenameField(
            model_name='personas',
            old_name='IdArea',
            new_name='AreaId',
        ),
        migrations.RenameField(
            model_name='problemas',
            old_name='IdArea',
            new_name='AreaId',
        ),
    ]
