# Generated by Django 4.2.6 on 2023-11-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reporte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reporte',
            new_name='Reportes',
        ),
    ]
