# Generated by Django 4.2.6 on 2023-11-03 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_rename_id_personas_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='user_id',
        ),
        migrations.AddField(
            model_name='personas',
            name='UserId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
