# Generated by Django 4.2.6 on 2023-11-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_personas_userid_personas_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personas',
            old_name='user_id',
            new_name='user',
        ),
    ]
