# Generated by Django 4.2.6 on 2023-11-03 23:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_personas_idpersona_personas_user_and_more'),
    ]

    operations = [
    ]
