# Generated by Django 4.2.6 on 2023-11-03 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_remove_personas_id_personas_idpersona'),
    ]

    operations = [
    ]
