# Generated by Django 4.2.6 on 2023-11-03 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_personas_user'),
    ]

    operations = [
    ]
