# Generated by Django 4.2.6 on 2023-11-04 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0026_rename_user_id_personas_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='per',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
