# Generated by Django 4.2.6 on 2023-11-04 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_personas_per'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personas',
            old_name='per',
            new_name='id',
        ),
    ]
