# Generated by Django 4.2.7 on 2023-11-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_personas_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='FechaF',
            field=models.DateTimeField(blank=True),
        ),
    ]
