# Generated by Django 4.2.7 on 2023-11-14 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_reportes_fechaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='FechaI',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 20, 3, 17, 406795, tzinfo=datetime.timezone.utc)),
        ),
    ]
