# Generated by Django 4.2.7 on 2023-11-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_reportes_fechai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='FechaF',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
