# Generated by Django 4.2.6 on 2023-11-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_areas_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='Folio',
            field=models.CharField(max_length=12),
        ),
    ]
