# Generated by Django 4.2.6 on 2023-11-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_reportes_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='Descripcion',
            field=models.CharField(default='abcdefghijklmnopqrstuvwxyz', max_length=1000),
        ),
    ]
