# Generated by Django 4.2.6 on 2023-11-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_reportes_folio'),
        ('api', '0038_reportes_descripcion'),
    ]

    operations = [
    ]
