# Generated by Django 4.2.6 on 2023-11-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_merge_20231117_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='Observaciones',
            field=models.CharField(default='observado', max_length=1000),
        ),
    ]
