# Generated by Django 4.2.6 on 2023-11-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_reportes_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='Acciones',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
