# Generated by Django 4.2.6 on 2023-11-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_servicios'),
        ('api', '0041_reportes_acciones'),
    ]

    operations = [
    ]
