# Generated by Django 4.2.6 on 2023-11-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_reportes_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportes',
            old_name='Tel',
            new_name='Num',
        ),
    ]
