# Generated by Django 4.2.6 on 2023-11-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_rename_tel_reportes_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportes',
            old_name='Num',
            new_name='nT',
        ),
    ]
