# Generated by Django 4.2.6 on 2023-11-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_rename_tel_reportes_ntel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportes',
            old_name='nTel',
            new_name='Cel',
        ),
    ]
