# Generated by Django 4.2.6 on 2023-11-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_rename_ntel_reportes_cel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportes',
            old_name='Cel',
            new_name='Contacto',
        ),
    ]
