# Generated by Django 4.2.6 on 2023-11-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_reportes_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='Contacto',
            field=models.CharField(default='7711111111', max_length=12),
        ),
    ]
