# Generated by Django 4.2.6 on 2023-11-24 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_reportes_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('IdOperacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Tipo', models.CharField(max_length=12)),
                ('Motivo', models.CharField(max_length=500)),
                ('PersonaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personas')),
                ('ReporteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportes')),
            ],
        ),
    ]
