# Generated by Django 4.2.6 on 2023-11-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_operaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='Activo',
            field=models.BooleanField(default=1),
        ),
    ]
