# Generated by Django 4.2.6 on 2023-11-27 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_reportes_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='HoraF',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reportes',
            name='HoraI',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportes',
            name='FechaI',
            field=models.DateField(auto_now_add=True),
        ),
    ]
