# Generated by Django 4.2.6 on 2023-11-27 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_reportes_horaf_reportes_horai_alter_reportes_fechai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='HoraF',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
