# Generated by Django 4.2.6 on 2024-01-12 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_reportes_fechaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='operaciones',
            name='Fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operaciones',
            name='Horafo',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
