# Generated by Django 4.2.6 on 2024-01-12 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_operaciones_fecha_operaciones_horafo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='FechaT',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
