# Generated by Django 4.2.6 on 2024-01-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_reportes_fechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='PersonaV',
            field=models.CharField(default='validado', max_length=250),
        ),
    ]
