# Generated by Django 4.2.6 on 2024-01-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_reportes_contf'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='Distrito',
            field=models.CharField(default='Pachuca', max_length=50),
        ),
    ]
